GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF0ZW8iLCJpYXQiOjE3MTg0NjQ4Mjl9.EYwoSVIDfSxH4DD4g-FnRdmLwGS8mCz607Crvxx7nx4


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Mateo"
}